include: package:lint/analysis_options.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    must_call_super: error
    invalid_use_of_protected_member: error
    parameter_assignments: error
    sort_unnamed_constructors_first: ignore
    avoid_bool_literals_in_conditional_expressions: ignore
    sort_pub_dependencies: ignore
    invalid_annotation_target: ignore
    always_use_package_imports: ignore
    avoid_redundant_argument_values: ignore
  exclude:
    - "pubspec.yaml"
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "injection.config.dart"
    - "router.gr.dart"
