name: quotes
description: "Random Quotes"

version: 1.0.0+1

environment:
  sdk: ^3.5.0 # current dart version from flutter --version
  flutter: ^3.24.0 # flutter version on 2024/08/16

dependencies:
  auto_route: ^8.3.0
  cloud_firestore: ^5.2.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  firebase_core: ^3.4.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.5.1
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.4.4
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.5.1
  json_annotation: ^4.9.0
  logging: ^1.2.0
  responsive_builder: ^0.7.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  analyzer: ^6.4.1
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.6.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.1
  lint: ^2.3.0
  mocktail: ^1.0.4
  riverpod_generator: ^2.4.0

# dart run flutter_launcher_icons:main
# flutter gen-l10n
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
